### ISSUE TITLE
Arduino_CAN des not work on M4 core

### ISSUE THREAD

**Issue by tineira** [arduino/ArduinoCore-mbed#787]
Neither read or write using Arduino_CAN works when running on the M4 core.

This is a POC code to write a message on the CAN network that works ok on the M7 and not on the M4. I intentionally left just the nessesary parts, not even calling RPC.h to try to isolate the issue.

When running this code LEDB keeps on, so I know it enters the loop. If I comment the CAN.write section, the loop works ok. This code works on with the same wiring on M7.

`// Lets make sure this code is loaded only into to core M7
#ifndef CORE_CM4
#error Expected to run on core M4
#endif

#include <Arduino_CAN.h>
//#include <RPC.h>

static uint32_t const CAN_ID = 200;

bool DI1 = true;
bool DI2 = false;
bool DI3 = true;
bool DI4 = false;
bool DI5 = true;
bool DI6 = false;
bool DI7 = true;
bool DI8 = false;

void setup()
{

  pinMode(LEDB, OUTPUT);

  //RPC.begin();
  //RPC.println("M4: Started");

  if (!CAN.begin(CanBitRate::BR_1000k))
  {
    //RPC.println("CAN.begin(...) failed.");
    for (;;) {}
  }
  //RPC.println("CAN.begin(...) success.");

}

void loop()
{

  //SEND

  /* Assemble a CAN message with the format of
   * 0xCA 0xFE 0x00 0x00 [4 byte message counter]
   */
  uint8_t const msg_data[] = {DI1,DI2,DI3,DI4,DI5,DI6,DI7,DI8};
  CanMsg msg(CanStandardId(CAN_ID), sizeof(msg_data), msg_data);

  /* Transmit the CAN message, capture and display an
   * error core in case of failure.
   */
  if (int const rc = CAN.write(msg); rc <= 0)
  {
    Serial.print  ("CAN.write(...) failed with error code ");
    Serial.println(rc);
    for (;;) { }
  }

  DI1 = !DI1;
  DI2 = !DI2;
  DI3 = !DI3;
  DI4 = !DI4;
  DI5 = !DI5;
  DI6 = !DI6;
  DI7 = !DI7;
  DI8 = !DI8;

  // BLINK
  static bool _blink = false;
  (_blink) ? digitalWrite(LEDB, HIGH) : digitalWrite(LEDB, LOW);
  _blink = !_blink;
  delay(500);    
        
  
}
`

**Comment by tineira** [comment]
I think I found something, maybe someone from Arduino can chip in.

When you compile something with M4 as a target, there is a file that loads all the definitions:
\AppData\Local\Arduino15\packages\arduino\hardware\mbed_giga\4.0.10\variants\GENERIC_STM32H747_M4\defines.txt

When the target is M7 this other file is loaded:
\AppData\Local\Arduino15\packages\arduino\hardware\mbed_giga\4.0.10\variants\GIGA\defines.txt

There are a few differences between those files, one of them is that for M7, there is a definition for TARGET_GIGA and for the M4 its TARGET_GENERIC_STM32H747_M4

Then, there is another file that configures what modules are enabled:
\AppData\Local\Arduino15\packages\arduino\hardware\mbed_giga\4.0.10\cores\arduino\mbed\targets\TARGET_STM\TARGET_STM32H7\STM32Cube_FW\stm32h7xx_hal_conf.h

on that file, if the target is not the M7, a lot of modules don't get enabled and one of them is #define HAL_FDCAN_MODULE_ENABLED so, this file does not get included #include "stm32h7xx_hal_fdcan.h".

Thinking it can be a problem with this configuration, I tried changing that file so all modules are enabled for the M4, and the program still didn't run.

I'm starting to think that maybe you can't access CANBUS from the M4, despite what the documentation says.
[Guide to GIGA R1 Dual Cores | Arduino Documentation](https://docs.arduino.cc/tutorials/giga-r1-wifi/giga-dual-core)

This topic is way over my head so maybe I'm missing something.

**Comment by facchinm** [comment]
Fixed by https://github.com/arduino/ArduinoCore-mbed/pull/774/commits/57d6f9af036ad79850360e583c666a2b18a2adb5 , will be available in next core release.

To test in the meantime with the core from git you can use this sketch (flash in both M7 and M4)
```
/**************************************************************************************
   INCLUDE
 **************************************************************************************/

#include <Arduino_CAN.h>
#include <SerialRPC.h>

/**************************************************************************************
   SETUP/LOOP
 **************************************************************************************/

void setup()
{
  SerialRPC.begin();
  while (!SerialRPC);

#ifdef CORE_CM7
  Serial.begin(115200);
  while (!Serial) { }
#else
  if (!CAN.begin(CanBitRate::BR_250k))
  {
    SerialRPC.println("CAN.begin(...) failed.");
    for (;;) {}
  }
#endif
}

void loop()
{
#ifdef CORE_CM7
  if (SerialRPC.available()) {
    Serial.write(SerialRPC.read());
  }
#else
  //static mbed::DigitalOut can_en(PE_3, 1);
  if (CAN.available())
  {
    CanMsg const msg = CAN.read();
    SerialRPC.println(msg);
  }
#endif
}
```

**Comment by tineira** [comment]
Hi,
thanks for your help, but it did not solve the issue for me at least. I changed the Arduino_CAN.h file with your commit, But that was not the issue as my code already compiled correctly, if that was not the case the error message directly below would have triggered.

I tested this two versions of code, one from the M4 core to handle CAN and the other from the M7. the M7 one works prefectly, with the other device on the CAN network receiving the messages. from the M4, the other device did not receive any messages. 

Also, if I try to CAN READ from the M4, the core hangs  (crashes), from the M7 there are no issues.


M4 CAN test code
```#ifdef CORE_CM7
// Core M7 code

  #include <RPC.h>
  
  void setup() {
      Serial.begin(115200);
      while(!Serial) ;
      
      RPC.begin();
  }

  void loop() {

    String buffer = "";
    while (RPC.available()) {
      buffer += (char)RPC.read();
    }
    if (buffer.length() > 0) {
      Serial.print(buffer);
    }
    delay(1000);
  }

#endif

/*------------------------------------------------------------------------------*/

#ifdef CORE_CM4
// Core M4 code

  #include <RPC.h>
  #include <Arduino_CAN.h>

  #define CAN_WRITE_EVERY 1000 

  // Write
  bool DI1 = true;
  bool DI2 = false;
  bool DI3 = true;
  bool DI4 = false;
  bool DI5 = true;
  bool DI6 = false;
  bool DI7 = true;
  bool DI8 = false;

  void changeValues(){
    //change values 
    DI1 = !DI1;
    DI2 = !DI2;
    DI3 = !DI3;
    DI4 = !DI4;
    DI5 = !DI5;
    DI6 = !DI6;
    DI7 = !DI7;
    DI8 = !DI8;
  }

  void canWork() {
    static unsigned long lastWriteMillis = 0;
   
    // CAN write
    if (lastWriteMillis + CAN_WRITE_EVERY < millis()) {
      // reset timer
      lastWriteMillis = millis();

      changeValues();

      RPC.println("Ready to send CAN Message");
      delay(50);
      // hardcoded can id
      static uint32_t const CAN_ID = 200;
      uint8_t const msg_data[] = {DI1,DI2,DI3,DI4,DI5,DI6,DI7,DI8};
      CanMsg msg(CanStandardId(CAN_ID), sizeof(msg_data), msg_data);
      CAN.write(msg);

      delay(50);
      RPC.println("CAN Message sent");
      delay(50);
      RPC.println("Waiting");
    }
  }

  void setup() {
    RPC.begin();
    RPC.println("M4: Started");

    if (!CAN.begin(CanBitRate::BR_1000k))
    {
      RPC.println("CAN.begin(...) failed.");
      for (;;) {}
    }

    RPC.println("Can begun");

  }

  void loop() {
    canWork();
    RPC.print(".");
    delay(100);
  }

#endif
```


M7 CAN test code
```#ifndef CORE_CM7
#error Must run on M7 Core
#endif

#include <Arduino_CAN.h>

  #define CAN_WRITE_EVERY 1000 

  // Write
  bool DI1 = true;
  bool DI2 = false;
  bool DI3 = true;
  bool DI4 = false;
  bool DI5 = true;
  bool DI6 = false;
  bool DI7 = true;
  bool DI8 = false;

  void changeValues(){
    //change values 
    DI1 = !DI1;
    DI2 = !DI2;
    DI3 = !DI3;
    DI4 = !DI4;
    DI5 = !DI5;
    DI6 = !DI6;
    DI7 = !DI7;
    DI8 = !DI8;
  }

  void canWork() {
    static unsigned long lastWriteMillis = 0;
   
    // CAN write
    if (lastWriteMillis + CAN_WRITE_EVERY < millis()) {
      // reset timer
      lastWriteMillis = millis();

      changeValues();

      Serial.println("Ready to send CAN Message");
      delay(50);
      // hardcoded can id
      static uint32_t const CAN_ID = 200;
      uint8_t const msg_data[] = {DI1,DI2,DI3,DI4,DI5,DI6,DI7,DI8};
      CanMsg msg(CanStandardId(CAN_ID), sizeof(msg_data), msg_data);
      CAN.write(msg);

      delay(50);
      Serial.println("CAN Message sent");
      delay(50);
      Serial.println("Waiting");
    }
  }

  void setup() {
      Serial.begin(115200);
      while(!Serial) ;

      if (!CAN.begin(CanBitRate::BR_1000k))
      {
        Serial.println("CAN.begin(...) failed.");
        for (;;) {}
      }

      Serial.println("Can begun");
  }


  void loop() {
    canWork();
    Serial.print(".");
    delay(100);
  }
```

Is it possible to mark this issue as OPEN again?
